enum Allergens: String, Codable, CaseIterable {
    case Eggs = "Ei"
    case Peanuts = "En"
    case Fish = "Fi"
    case Spelt = "GlD"
    case Barley = "GlG"
    case Oats = "GlH"
    case Kamut = "GlK"
    case Rye = "GlR"
    case Wheat = "GlW"
    case Crustaceans = "Kr"
    case Lupine = "Lu"
    case MilkLactose = "Mi"
    case CashewNuts = "NC"
    case Hazelnuts = "NH"
    case MacadamiaNuts = "NMc"
    case Almonds = "NMn"
    case BrazilNuts = "NPa"
    case Pecans = "NPe"
    case Pistachios = "NPi"
    case Walnuts = "NW"
    case Sesame = "Se"
    case Mustard = "Sf"
    case Celery = "Sl"
    case Soy = "So"
    case SulfurDioxide = "Sw"
    case Molluscs = "Wt"
}
