enum Location: String, CaseIterable {
    case MensaLuebeck = "HL_ME"
    case CafeteriaLuebeck = "HL_CA"
    case MusikhochschuleLuebeck = "HL_MH"
    case BitsAndBytes = "HL_BB"
    case Mensa1Kiel = "KI_ME1"
    case Cafeteria1Kiel = "KI_CA1"
    case Mensa2Kiel = "KI_ME2"
    case Cafeteria2Kiel = "KI_CA2"
    case KesselhausKiel = "KI_KESSELHAUS"
    case SchwentineMensaKiel = "KI_SCHWENTINE"
    case AmericanDinerKiel = "KI_DINER"
    case MensaDocksideKiel = "KI_DOCKSIDE"
    case MensaHeide = "HEI_ME1"
    case MensaFlensburg = "FL_ME1"
    case CafeteriaAFlensburg = "FL_CA1"
    case CafeteriaBFlensburg = "FL_CA2"
    case MensaOsterroenfeld = "RD_ME1"
    case CafeteriaWedel = "PI_CA1"
}
